services:
  # PHP 8.5 - ElarionStack Framework
  php:
    image: php:8.5-cli
    container_name: ${PROJECT_NAME:-elarionstack}_php85
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
    command:
      - bash
      - -c
      - |
        apt-get update && apt-get install -y \
          libzip-dev \
          libonig-dev \
          libxml2-dev \
          libicu-dev \
          git \
          unzip \
          curl &&
        docker-php-ext-install -j$$(nproc) \
          pdo \
          mbstring \
          pcntl \
          bcmath \
          zip \
          intl \
          soap \
          opcache &&
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
        git config --global --add safe.directory /var/www/html &&
        composer install --no-interaction --optimize-autoloader 2>/dev/null || echo "Composer dependencies not installed yet" &&
        tail -f /dev/null
